openapi: 3.1.0
info:
  title: Job Control Service
  version: 1.0.0
paths:
  /run-job:
    post:
      summary: Start a new job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sharedStateURL:
                  type: string
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      tasks:
                        type: array
                        items:
                          type: object
                          properties:
                            tag:
                              type: string
                            input:
                              type: object
                            storeResultAt:
                              oneOf:
                                - type: string
                                - type: object
                                  properties:
                                    sourcePath:
                                      type: string
                                    targetPath:
                                      type: string
                                    onlyOnStatus:
                                      type: array
                                      items:
                                        type: integer
                                - type: array
                                  items:
                                    type: object
                                    properties:
                                      sourcePath:
                                        type: string
                                      targetPath:
                                        type: string
                                      onlyOnStatus:
                                        type: array
                                        items:
                                          type: integer
      responses:
        '200':
          description: Job started
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  status:
                    type: string
        '500':
          description: Job failed
  /forms:
    get:
      summary: Get supported forms
      responses:
        '200':
          description: Available forms
